### ISSUE TITLE
[BUG] 关于vless+reality节点转化的一些问题

### ISSUE THREAD

**Issue by MuXia-0326** [asdlokj1qpi23/subconverter#33]
### 确认版本最新

- [X] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [X] 我已经确认之前没有issue涉及此BUG

### subconverter版本

SubConverter v0.9.7-7dec83d

### 转换过程

写死的mihomo配置转化为mihomo配置

### 转换设置

https://raw.githubusercontent.com/MuXia-0326/rule/master/clash/clash_config_vps.yml

### 复现步骤

将下面的节点信息通过转化器转化获得clash的配置信息

```yml
mixed-port: 7890
external-controller: :9090
external-ui: /ui
external-ui-url: 'https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip'
allow-lan: true
mode: rule
log-level: info
ipv6: false
dns:
  enable: true
  listen: 0.0.0.0:53
  nameserver:
    - 223.5.5.5
    - 223.6.6.6
  enhanced-mode: fake-ip
  # fake-ip:范围和过滤
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - +.msftconnecttest.com
    - +.msftncsi.com
    - +.xboxlive.com
    - msftconnecttest.com
    - xbox.*.microsoft.com
    - '*.battlenet.com.cn'
    - '*.battlenet.com'
    - '*.blzstatic.cn'
    - '*.battle.net'
    - 'time.microsoft.com'
    - 'time.apple.com'

geox-url:
  mmdb: 'https://github.com/Loyalsoldier/geoip/raw/release/Country.mmdb'

proxies:
  - name: vps-hk-vless
    type: vless
    server: hk.xxx.xyz
    port: 8858
    udp: true
    uuid: 5059df28-xxxx-c27604e7b64a
    flow: xtls-rprx-vision
    packet-encoding: xudp
    tls: true
    alpn:
      - h2
      - http/1.1
    servername: alist.xxxx.xyz
    client-fingerprint: chrome
    reality-opts:
      public-key: DT-xxxxxxx_7Izkkod2M7kDuzXBYtlknCcWA
      short-id: 81553xxxxxxdd4003
    network: tcp

proxy-groups:
  - name: proxy
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      -  vps-hk-vless

rules:
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,proxy
```

### 期望结果

- {name: 🇭🇰 vps-hk-vless, server: hk.xxxx.xyz, port: 8858, type: vless, uuid: 5059df28-xxxx-c27604e7b64a, tls: true, alpn: [h2, http/1.1], flow: xtls-rprx-vision, reality-opts: {public-key: DT-xxxxxxx_7Izkkod2M7kDuzXBYtlknCcWA, short-id:81553xxxxxxdd4003}, servername: alist.xxxx.xyz, client-fingerprint: chrome, network: tcp, udp: true}

### 实际结果

- {name: 🇭🇰 vps-hk-vless, server: hk.xxxx.xyz, port: 8858, type: vless, uuid: 5059df28-xxxx-c27604e7b64a, tls: true, alpn: [h2, http/1.1], flow: xtls-rprx-vision, reality-opts: {public-key: DT-xxxxxxx_7Izkkod2M7kDuzXBYtlknCcWA, short-id:“81553xxxxxxdd4003”}, servername: alist.xxxx.xyz, client-fingerprint: chrome, network: tcp, udp: true}

### 错误信息

```shell
short-id 转化后多了一层`""`包裹，导致无法被正确识别
```
